In [32]:
#%matplotlib widget
import numpy as np
import matplotlib.pyplot as plt
import os
import sys
import glob
import h5py as h5
from tabulate import tabulate
from datetime import date
import pandas as pd
from os import walk
import peakutils
from peakutils.plot import plot as pplot
from IPython.display import display, clear_output
#sys.path.append('/media/labfiles/lab-codes/lflm-labs-data/src')
from labexp import experiments
plt.style.use('/media/labfiles/lab-codes/plotstyle.mplstyle')
#path=r'/media/labfiles/lab-exps'


In [33]:
expname = '3-wells'
exp = experiments(1,'cry1','ras',expname)
data = exp.data
filesname=exp.filesname
paths=exp.pathname
folders = exp.foldername

|  No. Dir  | Name Dir                                         |  No. files  |
|-----------|--------------------------------------------------|-------------|
|     0     | cry-sys-1/3-wells/exp-2021-12/2021-12-14-ras     |      7      |
|     1     | cry-sys-1/3-wells/exp-2021-12/2021-12-16-ras     |      3      |
|     2     | cry-sys-1/3-wells/exp-2022-01/exp-2022-01-10-ras |      4      |


In [34]:
months = []
days = []
for i in range(len(paths)):
    if os.path.normpath(paths[i]).split(os.path.sep)[7] not in months:
        months.append(os.path.normpath(paths[i]).split(os.path.sep)[7])
    else: pass
    if os.path.normpath(paths[i]).split(os.path.sep)[8] not in days:
        days.append(os.path.normpath(paths[i]).split(os.path.sep)[8])
    else: pass


In [36]:
ld = os.listdir("/media/labfiles/lab-exps/spectro-lab/cry-sys-1/3-wells")
for i in ld:
    if ".opju" in i:
        print(i)
        ld.remove(i)
ld

['exp-2021-12', 'exp-2022-01']

In [37]:
lend = len(data)
maxdimrows = 0
maxdimcols = 0
dimlist = []
totaldims = []
for i in range(len(data)):
    lend2 = len(data[i])
    #print(lend2)
    if lend2 > 0:
        maxdimrows = max([len(j) for j in data[i]])
        maxdimcols = max([data[i][k].shape[1] for k in range(len(data[i]))])
        dimlist.append([maxdimrows,maxdimcols])

allarrs = []
for i in range(len(data)):
    lend2 = len(data[i])
    if lend2 != 0:
        npa = np.empty((dimlist[i][0],dimlist[i][1],lend2), dtype=np.float64)
        for j in range(lend2):
            rows,cols = data[i][j].shape
            npa[0:rows,0:cols,j] = data[i][j]
            
        allarrs.append(npa)
        

In [66]:
file = h5.File(expname+".h5",'a')
grps = []
dtsets = []
for i in range(len(months)):
    group = file.require_group(months[i])
    spltmonths = months[i].split('-',maxsplit=1)
    for j in range(len(days)):
        if spltmonths[1] in days[j]: 
            datas = group.require_dataset(days[j],shape=allarrs[j].shape,data=allarrs[j],dtype=np.float64) 
            dtsets.append(datas)
    grps.append(group)
    

dtsets

[<HDF5 dataset "2021-12-14-ras": shape (450, 4, 7), type "<f8">,
 <HDF5 dataset "2021-12-16-ras": shape (450, 4, 3), type "<f8">,
 <HDF5 dataset "exp-2022-01-10-ras": shape (500, 4, 4), type "<f8">]

In [95]:
len(data[0])

7

In [96]:
comp = file['exp-2021-12']['2021-12-14-ras'][0:250,:,1]
data[0][1][:]==comp

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
 

In [93]:
idx=0
for count,value in enumerate(os.listdir(pth)):
    for count2,value2 in enumerate(os.listdir(pth+ld[count])):
        try:
            f[value].create_group(value2)
            print(value,value2)
            idx+=1
            break
        except:
            pass

In [94]:
idx=0
for count,value in enumerate(os.listdir(pth)):
    for count2,value2 in enumerate(os.listdir(pth+ld[count])):
        try:
            #f[value].create_group(value2)
            f[value][value2].create_dataset("data",data=alla[idx], dtype=np.float64)
            print(f[value][value2])
            idx+=1
            break
        except:
            pass


In [62]:
comp = f['exp-2021-12/2021-12-14-ras/data'][:,:,0]
comp[:10]

array([[ 1.49325301e+00, -6.62789004e-04, -2.18280699e-03,
         1.44674047e-06],
       [ 1.49361292e+00, -5.94083937e-04, -2.19957695e-03,
         1.30673333e-06],
       [ 1.49397300e+00, -6.18473992e-04, -2.21573253e-03,
         1.37037294e-06],
       [ 1.49433325e+00, -5.87503145e-04, -2.23143652e-03,
         1.31097597e-06],
       [ 1.49469368e+00, -6.19432718e-04, -2.24883239e-03,
         1.39300036e-06],
       [ 1.49505428e+00, -6.56453914e-04, -2.26419315e-03,
         1.48633845e-06],
       [ 1.49541506e+00, -7.04787698e-04, -2.28148253e-03,
         1.60796082e-06],
       [ 1.49577601e+00, -7.13553938e-04, -2.29705623e-03,
         1.63907352e-06],
       [ 1.49613713e+00, -7.65902425e-04, -2.31546963e-03,
         1.77342381e-06],
       [ 1.49649843e+00, -7.17889834e-04, -2.32849157e-03,
         1.67160043e-06]])

In [65]:
data[0][0][:]==comp[:]

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
 

In [ ]:
lend = len(data)
maxdimrows = 0
maxdimcols = 0
dimlist = []
totaldims = []
for i in range(len(data)):
    lend2 = len(data[i])
    dummylist = []
    #print(lend2)
    if lend2 > 0:
        for j in range(lend2):
            #print(data[i][j].shape)
            if data[i][j].shape[0] > maxdimrows or data[i][j].shape[1] > maxdimcols:
                maxdimrows = data[i][j].shape[0]
                maxdimcols = data[i][j].shape[1]
            else:
                pass
            dimlist.append([maxdimrows,maxdimcols])
            dummylist.append(data[i][j].shape)   
        totaldims.append(dummylist)
        
alla = []     
idxc=0
for i in range(lend):
    lend2 = len(data[i])
    if lend2 != 0:
        print(lend2)
        npa = np.empty((dimlist[i][0],dimlist[i][1],lend2), dtype=np.float64)
        print(npa.shape)
        for j in range(lend2):
            rows,cols = totaldims[idxc][j]
            #print(rows,cols)
            if npa[0:rows,0:cols,j].shape == data[i][j].shape:
                #print(data[i][j].shape)
                #print(npa[0:rows,0:cols,j].shape)
                npa[0:rows,0:cols,j]=data[i][j]
        alla.append(npa)
        idxc+=1
    
# #define multidimensional array

7
(250, 4, 7)
3
(250, 4, 3)
4
(250, 4, 4)
